### ISSUE TITLE
Testcontainer issue: could not insert 'ip_tables': Operation not permitted

### ISSUE THREAD

**Issue by cmoulliard** [iocanel/openshift-vm-playground#1]
## Issue

Tekton task maven fails as testcontainer reports the following error:
```
2023-11-08 14:38:19,861 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-5) Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=tcp://10.128.2.169:2376
2023-11-08 14:38:19,864 INFO  [org.tes.DockerClientFactory] (build-5) Docker host IP address is 10.128.2.169
2023-11-08 14:38:19,961 INFO  [org.tes.DockerClientFactory] (build-5) Connected to docker: 
  Server Version: 4.6.2
  API Version: 1.41
  Operating System: fedora
  Total Memory: 1951 MB
2023-11-08 14:38:19,964 WARN  [org.tes.uti.ResourceReaper] (build-5) 
********************************************************************************
Ryuk has been disabled. This can cause unexpected behavior in your environment.
********************************************************************************
2023-11-08 14:38:19,967 INFO  [org.tes.DockerClientFactory] (build-5) Checking the system...
2023-11-08 14:38:19,968 INFO  [org.tes.DockerClientFactory] (build-5) ✔︎ Docker server version should be at least 1.6.0
2023-11-08 14:38:19,980 INFO  [org.tes.uti.ImageNameSubstitutor] (build-5) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2023-11-08 14:38:20,013 INFO  [🐳 .io/postgres:14]] (build-5) Pulling docker image: docker.io/postgres:14. Please be patient; this may take some time but only needs to be done once.
2023-11-08 14:38:34,722 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Starting to pull image
2023-11-08 14:38:35,090 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  5 pending,  1 downloaded,  0 extracted, (0 bytes/? MB)
2023-11-08 14:38:35,270 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  4 pending,  2 downloaded,  0 extracted, (0 bytes/? MB)
2023-11-08 14:38:35,787 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  4 pending,  3 downloaded,  0 extracted, (0 bytes/? MB)
2023-11-08 14:38:36,136 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  4 pending,  4 downloaded,  0 extracted, (7 MB/? MB)
2023-11-08 14:38:36,186 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  3 pending,  5 downloaded,  0 extracted, (7 MB/? MB)
2023-11-08 14:38:36,741 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  3 pending,  6 downloaded,  0 extracted, (7 MB/? MB)
2023-11-08 14:38:37,027 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  2 pending,  7 downloaded,  0 extracted, (23 MB/? MB)
2023-11-08 14:38:38,234 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  5 pending,  8 downloaded,  0 extracted, (34 MB/? MB)
2023-11-08 14:38:39,445 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  4 pending,  9 downloaded,  0 extracted, (48 MB/? MB)
2023-11-08 14:38:39,542 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  3 pending, 10 downloaded,  0 extracted, (48 MB/? MB)
2023-11-08 14:38:39,593 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  2 pending, 11 downloaded,  0 extracted, (48 MB/? MB)
2023-11-08 14:38:42,871 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  1 pending, 12 downloaded,  0 extracted, (119 MB/? MB)
2023-11-08 14:38:54,239 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  0 pending, 13 downloaded,  0 extracted, (119 MB/130 MB)
2023-11-08 14:38:54,327 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  0 pending, 14 downloaded,  0 extracted, (119 MB/130 MB)
2023-11-08 14:38:54,421 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pulling image layers:  0 pending, 14 downloaded,  0 extracted, (119 MB/130 MB)
2023-11-08 14:38:54,422 INFO  [🐳 .io/postgres:14]] (docker-java-stream--933788147) Pull complete. 14 layers, pulled in 19s (downloaded 119 MB at 6 MB/s)
2023-11-08 14:38:54,490 INFO  [🐳 .io/postgres:14]] (build-5) Creating container for image: docker.io/postgres:14
2023-11-08 14:38:54,509 WARN  [🐳 .io/postgres:14]] (build-5) Reuse was requested but the environment does not support the reuse of containers
To enable reuse of containers, you must set 'testcontainers.reuse.enable=true' in a file located at /root/.testcontainers.properties
2023-11-08 14:38:54,658 INFO  [🐳 .io/postgres:14]] (build-5) Container docker.io/postgres:14 is starting: 682f4bd0b0ac3ca5ee39b04905f760ac2428bd8998ad6105d8417dbc69964e73
2023-11-08 14:38:55,614 ERROR [🐳 .io/postgres:14]] (build-5) Could not start container: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"cause":"netavark (exit code 1): code: 3, msg: modprobe: ERROR: could not insert 'ip_tables': Operation not permitted\niptables v1.8.8 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n","message":"netavark (exit code 1): code: 3, msg: modprobe: ERROR: could not insert 'ip_tables': Operation not permitted\niptables v1.8.8 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n","response":500}

        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
 ```

**Comment by cmoulliard** [comment]
Questions ?

Should we see on the VM running the pôdman daemon a `ps` when testcontainer starts to create container ?
```
2023-11-09 08:38:40,780 INFO  [🐳 .io/postgres:14]] (build-30) Container docker.io/postgres:14 is starting: 5affaeebea8259fa845789c3d0d5f90f648dc3502c8e7039f3affa54750e8574
2023-11-09 08:38:40,944 ERROR [🐳 .io/postgres:14]] (build-30) Could not start container: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"cause":"netavark (exit code 1): code: 3, msg: modprobe: ERROR: could not insert 'ip_tables': Operation not permitted\niptables v1.8.8 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n","message":"netavark (exit code 1): code: 3, msg: modprobe: ERROR: could not insert 'ip_tables': Operation not permitted\niptables v1.8.8 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n","response":500}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
```
- Should we see the images downloaded by testcontainer within the VM when a testcase starts ?
```
2023-11-09 08:38:40,506 INFO  [org.tes.DockerClientFactory] (build-30) Checking the system...
2023-11-09 08:38:40,507 INFO  [org.tes.DockerClientFactory] (build-30) ✔︎ Docker server version should be at least 1.6.0
2023-11-09 08:38:40,519 INFO  [org.tes.uti.ImageNameSubstitutor] (build-30) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2023-11-09 08:38:40,618 INFO  [🐳 .io/postgres:14]] (build-30) Creating container for image: docker.io/postgres:14
...
[fedora@fedora37 ~]$ podman images
REPOSITORY                     TAG         IMAGE ID      CREATED        SIZE
quay.io/jitesoft/nginx         latest      d97edcb53747  2 weeks ago    55.9 MB
quay.io/podman/hello           latest      e2b3db5d4fdf  2 months ago   82.3 kB
docker.io/library/postgres     14          2d50489efff2  3 months ago   416 MB
docker.io/testcontainers/ryuk  0.3.4       7ac27de2f0c4  15 months ago  12.5 MB
quay.io/centos/centos          latest      300e315adb2f  2 years ago    217 MB
[fedora@fedora37 ~]$
```

**Comment by cmoulliard** [comment]
FYI: We can create a container remotely witin a pod 
```
kubectl exec -n development podman-client  -it -- /bin/sh
sh-5.2# podman -r --url=tcp://10.128.2.169:2376 run --name my-postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres
8a45aa2cc3f81dbef5ab5d4583f6190ea620672982bfc96788068da74886bb40
```
This is confirmed by podman inside the VM
```
[fedora@fedora37 ~]$ podman ps
CONTAINER ID  IMAGE                              COMMAND     CREATED             STATUS             PORTS                   NAMES
8a45aa2cc3f8  docker.io/library/postgres:latest  postgres    About a minute ago  Up About a minute  0.0.0.0:5432->5432/tcp  my-postgres
[fedora@fedora37 ~]$
```

**Comment by cmoulliard** [comment]
FYI
```
2023-11-09 11:33:21,714 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-106) Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=tcp://10.128.2.169:2376
2023-11-09 11:33:21,714 DEBUG [org.tes.doc.DockerClientProviderStrategy] (build-106) Transport type: 'httpclient5', Docker host: 'tcp://10.128.2.169:2376'
2023-11-09 11:33:21,714 DEBUG [org.tes.doc.DockerClientProviderStrategy] (build-106) Checking Docker OS type for Environment variables, system properties and defaults. Resolved dockerHost=tcp://10.128.2.169:2376
2023-11-09 11:33:21,716 INFO  [org.tes.DockerClientFactory] (build-106) Docker host IP address is 10.128.2.169
2023-11-09 11:33:21,717 DEBUG [org.tes.DockerClientFactory] (build-106) Docker info: {NGoroutines=13, BuildahVersion=1.31.2, Name=fedora37, Swarm={NodeID=, NodeAddr=, LocalNodeState=inactive, ControlAvailable=false, Error=, RemoteManagers=null}, RuncCommit={ID=, Expected=}, OSVersion=37, Runtimes={crun={path=/usr/bin/crun}, crun-wasm={path=/usr/bin/crun-wasm}, kata={path=/usr/bin/kata-runtime}, krun={path=/usr/bin/krun}, ocijail={path=/usr/local/bin/ocijail}, runc={path=/usr/bin/runc}, runj={path=/usr/local/bin/runj}, runsc={path=/usr/bin/runsc}, youki={path=/usr/local/bin/youki}}, ID=0067f0e3-1d65-4db4-8032-e5a2016cd0e4, DriverStatus=[[Supports d_type, true], [Native Overlay Diff, true], [Using metacopy, false], [Backing Filesystem, btrfs]], BridgeNfIptables=false, LiveRestoreEnabled=false, SystemTime=2023-11-09T11:33:21.175453443Z, NoProxy=, Architecture=amd64, NEventsListener=0, HttpsProxy=, Images=7, ContainersRunning=1, Labels=null, InitCommit={ID=, Expected=}, NFd=11, KernelVersion=6.0.7-301.fc37.x86_64, CPURealtimeRuntime=false, LoggingDriver=, OSType=linux, SecurityOptions=[name=seccomp,profile=default, name=rootless, name=selinux], ContainerdCommit={ID=, Expected=}, GenericResources=null, OperatingSystem=fedora, RegistryConfig={AllowNondistributableArtifactsCIDRs=[], AllowNondistributableArtifactsHostnames=[], InsecureRegistryCIDRs=[], IndexConfigs={}, Mirrors=[]}, ServerVersion=4.6.2, OomKillDisable=false, CpuCfsQuota=false, Containers=1, Driver=overlay, IPv4Forwarding=false, ExperimentalBuild=true, ProductLicense=Apache-2.0, DockerRootDir=/home/fedora/.local/share/containers/storage, CPUSet=false, CpuCfsPeriod=false, DefaultRuntime=crun, SwapTotal=2045767680, CPUShares=false, Debug=false, NCPU=1, Plugins={Volume=[local], Network=[bridge, macvlan, ipvlan], Authorization=null, Log=[k8s-file, none, passthrough, journald]}, SwapLimit=false, CgroupDriver=systemd, Uptime=24h 56m 49.00s (Approximately 1.00 days), SwapFree=2042884096, Rootless=true, ContainersPaused=0, MemTotal=2046070784, IndexServerAddress=, MemoryLimit=true, HttpProxy=, InitBinary=, CPURealtimePeriod=false, CgroupVersion=2, PidsLimit=true, Isolation=, BridgeNfIp6tables=false, Warnings=[], ContainersStopped=0}
2023-11-09 11:33:21,719 DEBUG [org.tes.sha.com.git.doc.cor.com.AbstrDockerCmd] (build-106) Cmd: 
2023-11-09 11:33:21,867 DEBUG [org.tes.DockerClientFactory] (build-106) Docker version: {Components=[{Name=Podman Engine, Version=4.6.2, Details={APIVersion=4.6.2, Arch=amd64, BuildTime=2023-08-28T19:38:31Z, Experimental=false, GitCommit=, GoVersion=go1.19.12, KernelVersion=6.0.7-301.fc37.x86_64, MinAPIVersion=4.0.0, Os=linux}}, {Name=Conmon, Version=conmon version 2.1.7, commit: , Details={Package=conmon-2.1.7-2.fc37.x86_64}}, {Name=OCI Runtime (crun), Version=crun version 1.9.2
commit: 35274d346d2e9ffeacb22cc11590b0266a23d634
rundir: /run/user/1000/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL, Details={Package=crun-1.9.2-1.fc37.x86_64}}], KernelVersion=6.0.7-301.fc37.x86_64, ApiVersion=1.41, Platform={Name=linux/amd64/fedora-37}, GitCommit=, Os=linux, Version=4.6.2, MinAPIVersion=1.24, Arch=amd64, GoVersion=go1.19.12, BuildTime=2023-08-28T19:38:31Z}
2023-11-09 11:33:21,867 INFO  [org.tes.DockerClientFactory] (build-106) Connected to docker: 
  Server Version: 4.6.2
  API Version: 1.41
  Operating System: fedora
  Total Memory: 1951 MB
2023-11-09 11:33:21,871 WARN  [org.tes.uti.ResourceReaper] (build-106) 
********************************************************************************
Ryuk has been disabled. This can cause unexpected behavior in your environment.
********************************************************************************
```

**Comment by cmoulliard** [comment]
Here is what podman log (= journalctl) reports when testcontainer tries to create a container
```
Nov 09 18:00:07 fedora37 systemd[2030]: Starting podman.service - Podman API Service...
Nov 09 18:00:07 fedora37 systemd[2030]: Started podman.service - Podman API Service.
Nov 09 18:00:07 fedora37 podman[45959]: time="2023-11-09T18:00:07Z" level=info msg="/usr/bin/podman filtering at log level info"
Nov 09 18:00:07 fedora37 podman[45959]: time="2023-11-09T18:00:07Z" level=info msg="Setting parallel job count to 4"
Nov 09 18:00:07 fedora37 podman[45959]: time="2023-11-09T18:00:07Z" level=info msg="Using systemd socket activation to determine API endpoint"
Nov 09 18:00:07 fedora37 podman[45959]: time="2023-11-09T18:00:07Z" level=info msg="API service listening on \"/run/user/1000/podman/podman.sock\". URI: \"/run/user/1000/podman/podman.sock\""
Nov 09 18:00:07 fedora37 podman[45959]: time="2023-11-09T18:00:07Z" level=warning msg="IdleTracker: StateClosed transition by connection marked un-managed" X-Reference-Id=0xc000580820
Nov 09 18:00:08 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:08 +0000] "GET /v1.32/info HTTP/1.1" 200 2367 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:08 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:08 +0000] "GET /v1.32/version HTTP/1.1" 200 928 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:08 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:08 +0000] "GET /v1.32/images/json HTTP/1.1" 200 6881 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:08 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:08 +0000] "GET /v1.32/images/docker.io%2Fpostgres:14/json HTTP/1.1" 200 4284 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:08 fedora37 podman[45959]: 2023-11-09 18:00:08.852881652 +0000 UTC m=+1.021569281 volume create 5ea04da7d6fdb59eddd58fe4887e66236db805dbfc684bd6cb84dfdcca7d0057
Nov 09 18:00:08 fedora37 podman[45959]: 2023-11-09 18:00:08.873581441 +0000 UTC m=+1.042269197 container create c49ca25af9eb5d6657bfc4cc83f86651949050ee785316b5d6b88f37e16f6f02 (image=docker.io/library/postgres:14, name=zen_lumiere, org.testcontainers.lang=java, datasource=default, org.testcontainers.version=1.17.6, org.testcontainers.sessionId=aa58cddf-464c-414d-98a8-8cd9edf05ad4, org.testcontainers=true)
Nov 09 18:00:08 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:08 +0000] "POST /v1.32/containers/create HTTP/1.1" 201 88 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:08 fedora37 podman[45991]: [INFO  netavark::firewall] Using iptables firewall driver
Nov 09 18:00:08 fedora37 kernel: podman0: port 1(veth0) entered blocking state
Nov 09 18:00:08 fedora37 kernel: podman0: port 1(veth0) entered disabled state
Nov 09 18:00:08 fedora37 kernel: device veth0 entered promiscuous mode
Nov 09 18:00:08 fedora37 audit: ANOM_PROMISCUOUS dev=veth0 prom=256 old_prom=0 auid=1000 uid=1000 gid=1000 ses=2
Nov 09 18:00:08 fedora37 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Nov 09 18:00:08 fedora37 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth0: link becomes ready
Nov 09 18:00:08 fedora37 podman[45991]: [INFO  netavark::network::netlink] Adding route (dest: 0.0.0.0/0 ,gw: 10.88.0.1, metric 100)
Nov 09 18:00:08 fedora37 kernel: podman0: port 1(veth0) entered blocking state
Nov 09 18:00:08 fedora37 kernel: podman0: port 1(veth0) entered forwarding state
Nov 09 18:00:08 fedora37 kernel: podman0: port 1(veth0) entered disabled state
Nov 09 18:00:08 fedora37 kernel: device veth0 left promiscuous mode
Nov 09 18:00:08 fedora37 kernel: podman0: port 1(veth0) entered disabled state
Nov 09 18:00:08 fedora37 audit: ANOM_PROMISCUOUS dev=veth0 prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295
Nov 09 18:00:09 fedora37 podman[45959]: time="2023-11-09T18:00:09Z" level=info msg="Request Failed(Internal Server Error): netavark (exit code 1): code: 3, msg: modprobe: ERROR: could not insert 'ip_tables': Operation not permitted\niptables v1.8.8 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n"
Nov 09 18:00:09 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:08 +0000] "POST /v1.32/containers/c49ca25af9eb5d6657bfc4cc83f86651949050ee785316b5d6b88f37e16f6f02/start HTTP/1.1" 500 595 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:09 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:09 +0000] "GET /v1.32/containers/c49ca25af9eb5d6657bfc4cc83f86651949050ee785316b5d6b88f37e16f6f02/logs?stdout=true&stderr=true&since=0 HTTP/1.1" 200 0 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:09 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:09 +0000] "GET /v1.32/containers/json?all=true&filters=%7B%22label%22%3A%5B%22org.testcontainers%3Dtrue%22%2C%22org.testcontainers.lang%3Djava%22%2C%22org.testcontainers.version%3D1.17.6%22%2C%22org.testcontainers.sessionId%3Daa58cddf-464c-414d-98a8-8cd9edf05ad4%22%5D%7D HTTP/1.1" 200 1293 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:09 fedora37 podman[45959]: 2023-11-09 18:00:09.349826341 +0000 UTC m=+1.518514037 container remove c49ca25af9eb5d6657bfc4cc83f86651949050ee785316b5d6b88f37e16f6f02 (image=docker.io/library/postgres:14, name=zen_lumiere, org.testcontainers=true, org.testcontainers.lang=java, org.testcontainers.sessionId=aa58cddf-464c-414d-98a8-8cd9edf05ad4, org.testcontainers.version=1.17.6, datasource=default)
Nov 09 18:00:09 fedora37 podman[45959]: 2023-11-09 18:00:09.362388174 +0000 UTC m=+1.531075856 volume remove 5ea04da7d6fdb59eddd58fe4887e66236db805dbfc684bd6cb84dfdcca7d0057
Nov 09 18:00:09 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:09 +0000] "DELETE /v1.32/containers/c49ca25af9eb5d6657bfc4cc83f86651949050ee785316b5d6b88f37e16f6f02?v=true&force=true HTTP/1.1" 204 0 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:09 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:09 +0000] "POST /v1.32/networks/prune?filters=%7B%22label%22%3A%5B%22org.testcontainers%3Dtrue%22%2C%22org.testcontainers.lang%3Djava%22%2C%22org.testcontainers.version%3D1.17.6%22%2C%22org.testcontainers.sessionId%3Daa58cddf-464c-414d-98a8-8cd9edf05ad4%22%5D%7D HTTP/1.1" 200 23 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:09 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:09 +0000] "POST /v1.32/volumes/prune?filters=%7B%22label%22%3A%5B%22org.testcontainers%3Dtrue%22%2C%22org.testcontainers.lang%3Djava%22%2C%22org.testcontainers.version%3D1.17.6%22%2C%22org.testcontainers.sessionId%3Daa58cddf-464c-414d-98a8-8cd9edf05ad4%22%5D%7D HTTP/1.1" 200 41 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
Nov 09 18:00:09 fedora37 podman[45959]: @ - - [09/Nov/2023:18:00:09 +0000] "POST /v1.32/images/prune?filters=%7B%22label%22%3A%5B%22org.testcontainers%3Dtrue%22%2C%22org.testcontainers.lang%3Djava%22%2C%22org.testcontainers.version%3D1.17.6%22%2C%22org.testcontainers.sessionId%3Daa58cddf-464c-414d-98a8-8cd9edf05ad4%22%5D%7D HTTP/1.1" 200 40 "" "Apache-HttpClient/5.0.3 (Java/14.0.2)"
```

**Comment by cmoulliard** [comment]
I fixed the issue after executing within the VM = Fedora38 `sudo modprobe iptable-nat`. To be retested of course

![Screenshot 2023-11-09 at 19 34 46](https://github.com/iocanel/openshift-vm-playground/assets/463790/062b548f-322b-4d2f-9335-53f3541c79a8)
